### ISSUE TITLE
让部署环境变得简单：docker安装rabbitmq，docker-compose挂载配置启动

### ISSUE THREAD

**Issue by knecy** [knecy/me#12]
由于项目需要，所以在本地vm建立了基于centos7的运行环境，统一使用docker镜像，docker-compose部署
原先打算在windows环境安装和启用rabbitmq，发现还需要安装erlang语言环境，嫌麻烦，想想本地vm装过centos系统，遂祭出神器docker来搞定rabbitmq的service，在此留个爪印填个坑
rabbitmq镜像就使用最新版本
docker-compose配置就如此配
```
version: '3'
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    volumes:
      - ../data/rabbitmq/etc:/etc/rabbitmq
      - ../data/rabbitmq/var/lib:/var/lib/rabbitmq
      - ../data/rabbitmq/var/log:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
```
需要注意的是rabbitmq的配置在环境中涉及到2个地方：/etc/rabbitmq目录和/var/lib/rabbitmq目录下
我在配置中把这2个配置所在目录挂载出来作为持久化，哦，还有log目录也是
如果需要用到rabbitmq的管理页面，则需要在容器启动后执行：
```
rabbitmq-plugins enable rabbitmq_management
rabbitmqctl start_app
```
也可以在外面配置脚本挂载进容器启动执行
