### ISSUE TITLE
让部署环境变得简单：docker安装mongodb，docker-compose挂载配置启动镜像

### ISSUE THREAD

**Issue by knecy** [knecy/me#13]
续前篇，vm的centos7虚机中装环境
docker-compose配置文件如下：
```
version: '2'
services:
    mongodb:
        image: docker.io/mongo:latest
        container_name: "mongodb"
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/data/logs
        volumes:
            - ../data/mongodb/data:/data/db
            - ../data/mongodb/logs:/data/logs
        ports:
            - 27017:27017            
```
声明并挂载了数据文件和logs
