### ISSUE TITLE
让部署环境变得简单：docker安装redis，docker-compose配置文件启动

### ISSUE THREAD

**Issue by knecy** [knecy/me#14]
续前篇，redis的docker-compose配置文件：
```
version: '3'
services:
  redis:
    image: docker.io/redis:latest
    container_name: docker_redis
    volumes:
      - ..data/redis/datadir:/data
      - ..data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ..data/redis/logs:/logs
    ports:
      - 6379:6379
```
依然用的最新版本镜像，data目录挂载数据，conf目录挂载配置文件，logs挂载日志
