### ISSUE TITLE
让部署环境变得简单：docker安装elasticsearch搜索服务，docker-compose挂载配置镜像启动

### ISSUE THREAD

**Issue by knecy** [knecy/me#15]
续前篇，感觉这个镜像是我用到现在为止占空间比较大的一个，接近1G，还是和其是由java开发有关
docker-compose配置文件如下：
```
version: '3.7'
services:
  es:
    image: docker.io/elasticsearch:7.8.0
    container_name: elasticsearch
    restart: always
    environment:
      - "discovery.type=single-node"
    volumes:
      - ..data/elasticsearch/data:/usr/share/elasticsearch/data
      - ..data/elasticsearch/config:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
      - 9300:9300
```
data目录为其数据目录，config是配置目录
